# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('0', 'In progress'), ('1', 'Submitted'), ('2', 'Under development'), ('3', 'Under testing'), ('4', 'Authorized')], max_length=1)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('risks', models.TextField(blank=True, null=True)),
                ('submited_date', models.DateTimeField(blank=True, null=True)),
                ('under_dev_date', models.DateTimeField(blank=True, null=True)),
                ('under_testing_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('tesing_report', models.TextField(blank=True, null=True)),
                ('developer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_for_dev', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_forms', to=settings.AUTH_USER_MODEL)),
                ('tester', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_for_testing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
