# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formgenerator',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_for_dev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formgenerator',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_for_testing', to=settings.AUTH_USER_MODEL),
        ),
    ]
