# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_forminstance_form_generator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forminstance',
            name='form_generator',
        ),
        migrations.AlterField(
            model_name='formgenerator',
            name='submited_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
